name       : ccache
version    : 3.3.4
release    : 12
source     :
    - https://www.samba.org/ftp/ccache/ccache-3.3.4.tar.gz : 1348b54e7c35dd2f8d17923389e03c546e599cfbde6459d2f31cf6f1521ec538
homepage   : http://ccache.samba.org/
license    : GPL-3.0
summary    : compiler cache
component  : programming.tools
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
