name       : ccache
version    : 3.3
release    : 10
source     :
    - https://www.samba.org/ftp/ccache/ccache-3.3.tar.xz : d88e6f5f62f9ce5eeee673972a5731f76e22a5c708cfbc264ecd25a93fffba07
homepage   : http://ccache.samba.org/
license    :
    - GPL-3.0
summary    : compiler cache
component  : programming.tools
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
