name       : ccache
version    : 4.8.3
release    : 26
source     :
    - https://github.com/ccache/ccache/releases/download/v4.8.3/ccache-4.8.3.tar.gz : d59dd569ad2bbc826c0bc335c8ebd73e78ed0f2f40ba6b30069347e63585d9ef
homepage   : https://ccache.dev/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
builddeps  :
    - pkgconfig(libzstd)
    - asciidoctor
setup      : |
    %patch -p1 < $pkgfiles/0001-ccache-Add-vendor-dir.patch
    %cmake_ninja -DCMAKE_INSTALL_SYSCONFDIR="/etc/ccache" \
                 -DVENDORDIR="/usr/share/defaults/etc/ccache" \
                 -DREDIS_STORAGE_BACKEND=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done

    install -Dm00644 $pkgfiles/ccache.conf -t $installdir/usr/share/defaults/etc/ccache
check      : |
    %ninja_check
