name        : ccache
version     : 3.2.2
release     : 9
source      :
    - http://samba.org/ftp/ccache/ccache-3.2.2.tar.xz : 4f0d99699f24d198494addca0f41a93b0150cdfd01491f15a5d7eb02c7c2a0ca
homepage    : http://ccache.samba.org/
license     :
    - GPL-3.0
summary     : compiler cache
description : |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    
    install -d $installdir/%libdir%/ccache/bin
    
    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
