name       : ccache
version    : 4.5.1
release    : 21
source     :
    - https://github.com/ccache/ccache/releases/download/v4.5.1/ccache-4.5.1.tar.xz : 51186ebe0326365f4e6131e1caa8911de7da4aa6718efc00680322d63a759517
homepage   : http://ccache.samba.org/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
builddeps  :
    - pkgconfig(hiredis)
    - pkgconfig(libzstd)
    - asciidoctor
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
check      : |
    %ninja_check
