name       : ccache
version    : 4.7.4
release    : 24
source     :
    - https://github.com/ccache/ccache/releases/download/v4.7.4/ccache-4.7.4.tar.gz : dc283906b73bd7c461178ca472a459e9d86b5523405035921bd8204e77620264
homepage   : http://ccache.samba.org/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
builddeps  :
    - pkgconfig(libzstd)
    - asciidoctor
setup      : |
    %cmake_ninja \
        -DCMAKE_INSTALL_SYSCONFDIR="/etc/ccache" \
        -DREDIS_STORAGE_BACKEND=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done

    install -Dm00644 $pkgfiles/ccache.conf -t $installdir/etc/ccache
check      : |
    %ninja_check
