name       : ccache
version    : '4.3'
release    : 19
source     :
    - https://github.com/ccache/ccache/releases/download/v4.3/ccache-4.3.tar.xz : 504a0f2184465c306826f035b4bc00bae7500308d6af4abbfb50e33a694989b4
homepage   : http://ccache.samba.org/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
builddeps  :
    - pkgconfig(libzstd)
    - asciidoc
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
check      : |
    %ninja_check
