name       : ccache
version    : 3.7.5
release    : 17
source     :
    - https://github.com/ccache/ccache/releases/download/v3.7.5/ccache-3.7.5.tar.gz : 058cc18a25d57c0fd9aa494efdee3cc567b1b60ba1c80a18c5a0128c23832c09
homepage   : http://ccache.samba.org/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : compiler cache
description: |
    ccache is a compiler cache. It speeds up recompilation by caching previous compilations and detecting when the same compilation is being done again. Supported languages are C, C++, Objective-C and Objective-C++.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install

    install -d $installdir/%libdir%/ccache/bin

    TGT="$installdir/%libdir%/ccache/bin"
    for compiler in gcc x86_64-solus-linux-gcc g++ x86_64-solus-linux-g++ c++ x86_64-solus-linux-c++ clang clang++ ; do
        ln -sv /usr/bin/ccache "${TGT}/${compiler}"
    done
check      : |
    %make check
